version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: ${ERLANG_COOKIE}
      RABBITMQ_NODENAME: "rabbit@rabbitmq1"
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq1_data:/var/lib/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      rabbitmq_cluster:
        aliases:
          - rabbitmq1

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: ${ERLANG_COOKIE}
      RABBITMQ_NODENAME: "rabbit@rabbitmq2"
      CLUSTER_HOST: "rabbitmq1"
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq2_data:/var/lib/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      rabbitmq_cluster:
        aliases:
          - rabbitmq2

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: ${ERLANG_COOKIE}
      RABBITMQ_NODENAME: "rabbit@rabbitmq3"
      CLUSTER_HOST: "rabbitmq1"
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq3_data:/var/lib/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      rabbitmq_cluster:
        aliases:
          - rabbitmq3

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      rabbitmq_cluster:
        aliases:
          - haproxy

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:

networks:
  rabbitmq_cluster:
    driver: bridge